.TH GPOMME 1 "2006-12-24"
.SH NAME
gpomme \- GTK+ graphical client for use with pommed

.SH SYNOPSIS
.B wmpomme
.BI [\-r \ time ]
.B [\-v]
.SH DESCRIPTION
.B gpomme
will react to signals sent by
.B pommed
over DBus when a key is pressed, displaying the action taken by
.B pommed
and the current state associated with this action.

.SH OPTIONS
.B gpomme
accepts no command line options.

.SH AUTHOR
.B gpomme
was written by Julien BLACHE <jb@jblache.org> and Soeren SONNENBURG <debian@nn7.de>
based on code taken from
.B gtkpbbuttons

.SH SEE ALSO
pommed(1)
