.TH WMPOMME 1 "2008-11-09"
.SH NAME
wmpomme \- WindowMaker dockapp for use with pommed

.SH SYNOPSIS
.B wmpomme
.BI [\-r \ time ]
.B [\-v]
.SH DESCRIPTION
.B wmpomme
displays, as a WindowMaker dockapp, the state of the devices controlled by
.B pommed

.SH OPTIONS
.TP
.BI \-v
Display the version
.TP
.BI \-display \ display
This option specifies the X server to contact; see X(1).

.SH AUTHOR
.B wmpomme
was written by Julien BLACHE <jb@jblache.org>, based on
.B wmwave
by Carsten Schuermann <carsten@schuermann.org>

.SH SEE ALSO
pommed(1)
